spring:
  jwt:
    secret: yonsei-maist
jasypt:
  encryptor:
    bean: stringEncryptor
---
spring:
  profiles: local
  datasource:
    url: jdbc:mysql://maist.yonsei.ac.kr:3306/default?characterEncoding=UTF-8&serverTimezone=UTC
    username: ENC(Cvcn+bF7A34Hbv0J7Q7qcIcL9XQ9liCTA9EXWonO/SA=)
    password: ENC(M0DDtiCS0DIXQIwHY6CIKUCIIquJknCWhdLy4nJOMqPuZopWSw0l1ru1Y8aH7ojO)
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    mode: HTML
    cache: false
    template-resolver-order: 0
  servlet:
    multipart:
      max-file-size: 10MB
logging:
  pattern:
    console: "%d %-5level %logger{30}:%line - %msg%n"
  level:
    org.hibernate.type: trace
server:
  port: 8080
---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://maist.yonsei.ac.kr:3306/default?characterEncoding=UTF-8&serverTimezone=UTC
    username: ENC(Cvcn+bF7A34Hbv0J7Q7qcIcL9XQ9liCTA9EXWonO/SA=)
    password: ENC(M0DDtiCS0DIXQIwHY6CIKUCIIquJknCWhdLy4nJOMqPuZopWSw0l1ru1Y8aH7ojO)
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    mode: HTML
    cache: false
    template-resolver-order: 0
  servlet:
    multipart:
      max-file-size: 10MB
logging:
  pattern:
    console: "%d %-5level %logger{30}:%line - %msg%n"
  level:
    org.hibernate.type: debug
server:
  port: 8080